# Generated by Django 3.0.8 on 2020-08-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
