# Generated by Django 3.0.8 on 2020-08-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200805_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='upVote',
            new_name='upvote',
        ),
    ]
